import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>JDIH Kemlu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* MAIN HERO SECTION */}
        <section className='bg-[url("/images/homepage/img-background-hero.png")] h-[calc(100vh-60px)] bg-cover bg-center bg-no-repeat relative text-white'>
          {/* overlay */}
          <div className='absolute top-0 left-0 w-full h-full bg-gradient-to-b from-primary-700/90 to-primary-700/40 z-0' aria-hidden />
          {/* content */}
          <div className='h-full w-full flex flex-col items-center justify-center relative'>
            <h1 className='uppercase text-center mb-7'>
              Jaringan Dokumentasi dan Informasi Hukum<br />
              Kementrian Luar Negeri
            </h1>
            <p className='text-neutral-200'>Temukan Informasi dan Dokumentasi Hukum Terkini dari Kementrian Luar Negeri</p>
            <input type='text' className='mb-7' />
            <p className='font-medium mb-7 text-neutral-100'>Pencarian Populer Dokumen Hukum JDIH</p>
          </div>
        </section>
      </main>
    </div>
  )
}
